# Site Settings
title: Lions Volley Latina
tagline: "La pallavolo a Latina ha un solo nome: Lions!"
email: lionsvolleylatina@gmail.com
description: >
  Societ√† di Pallavolo di Latina
baseurl: ""
url: "https://www.lionsvolleylatina.it"
permalink: pretty
social:
  name: Lions Volley Latina
  links:
    - https://www.facebook.com/Lionsvolleylatina/
locale: it_IT
image: https://www.lionsvolleylatina.it/img/home.jpg
google_analytics: G-ZM76D26Q46

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: ""
      layout: post
      image: /img/home.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "sponsors"
    values:
      layout: "sponsors"
  -
    scope:
      path: ""
      type: "teams"
    values:
      layout: "teams"
  -
    scope:
      path: ""
      type: "staffs"
    values:
      layout: "staffs"

collections:
  authors:
    output: true
  sponsors:
    output: true
  teams:
    output: true
  staffs:
    output: true